# Generated by Django 5.1.3 on 2024-11-28 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_price',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_quantity',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
