# Generated by Django 5.1.3 on 2025-02-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='comment',
            field=models.TextField(max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='second_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
