# Generated by Django 5.1.3 on 2024-11-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_crop_crop_price_crop_crop_quantity_alter_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_price',
            field=models.IntegerField(default=0),
        ),
    ]
