# Generated by Django 5.1.3 on 2025-03-12 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_crop_comment_crop_second_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.farm'),
        ),
    ]
