# Generated by Django 5.1.3 on 2024-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_crop_crop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
