# Generated by Django 5.1.3 on 2024-11-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_crop_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='date',
        ),
    ]
