# Generated by Django 5.1.3 on 2024-11-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_crop_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='crop_quantity',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='crop_price',
        ),
        migrations.AddField(
            model_name='crop',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(default=0, upload_to='crop_images/'),
            preserve_default=False,
        ),
    ]
