# Generated by Django 5.1.3 on 2024-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_crop_name_crop_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crop',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
